# Generated by Django 2.2 on 2019-04-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='city',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Bangluru', 'Bangluru')], default='Delhi', max_length=30),
        ),
    ]
